version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jquery"
        versions: [">=4.0.0"]
      - dependency-name: "bootstrap"
        versions: [">=5.0.0"]
